import Foundation
@testable import SplynekCore

/// v0.41 added Pro license gating. The validator is the security +
/// UX linchpin — a silently-broken validator either hands Pro out
/// to the whole free tier or bricks legitimate buyers. These tests
/// pin:
///   - the Swift `LicenseValidator.issue(...)` output against a
///     known-good fixture generated by `Scripts/gen-license.py`;
///   - round-trip (issue + validate) for a handful of emails;
///   - the obvious negative cases (wrong email, tampered key,
///     empty inputs, trailing-whitespace tolerance);
///   - the `LicenseManager` state machine (init → unlock → persist
///     → deactivate) using an isolated UserDefaults suite so the
///     dev's real `splynekProEmail` / `splynekProKey` aren't
///     touched.
enum LicenseValidatorTests {

    static func run() {
        TestHarness.suite("License validator") {

            TestHarness.test("Swift issue() matches Python gen-license.py fixture") {
                // `python3 Scripts/gen-license.py test@splynek.app` must
                // produce exactly this key. If either side drifts the
                // validator stops recognising Stripe-issued keys.
                try expectEqual(
                    LicenseValidator.issue(email: "test@splynek.app"),
                    "SPLYNEK-250B-54AA-8108-AB17-ACA7"
                )
            }

            TestHarness.test("issue is stable across calls for the same email") {
                let a = LicenseValidator.issue(email: "a@b.com")
                let b = LicenseValidator.issue(email: "a@b.com")
                try expectEqual(a, b)
            }

            TestHarness.test("Email normalisation: case + whitespace are ignored") {
                let canonical = LicenseValidator.issue(email: "user@example.com")
                // Capitalisation:
                try expect(LicenseValidator.validate(
                    email: "User@Example.COM", key: canonical
                ))
                // Trailing newline (paste artefact):
                try expect(LicenseValidator.validate(
                    email: "user@example.com\n", key: canonical
                ))
                // Trailing spaces on the key:
                try expect(LicenseValidator.validate(
                    email: "user@example.com", key: canonical + "  "
                ))
            }

            TestHarness.test("Different emails produce different keys") {
                let a = LicenseValidator.issue(email: "a@x.com")
                let b = LicenseValidator.issue(email: "b@x.com")
                try expect(a != b, "expected distinct keys, both were \(a)")
            }

            TestHarness.test("Tampered key is rejected") {
                let k = LicenseValidator.issue(email: "a@x.com")
                // Flip the last hex group.
                let tampered = String(k.dropLast(4)) + "FFFF"
                try expect(!LicenseValidator.validate(email: "a@x.com", key: tampered))
            }

            TestHarness.test("Correct key for wrong email is rejected") {
                let k = LicenseValidator.issue(email: "a@x.com")
                try expect(!LicenseValidator.validate(email: "b@x.com", key: k))
            }

            TestHarness.test("Empty key / email inputs are rejected") {
                try expect(!LicenseValidator.validate(email: "", key: ""))
                try expect(!LicenseValidator.validate(email: "a@x.com", key: ""))
                try expect(!LicenseValidator.validate(email: "", key: "SPLYNEK-AAAA-BBBB-CCCC-DDDD-EEEE"))
            }

            TestHarness.test("Key format: SPLYNEK-AAAA-BBBB-CCCC-DDDD-EEEE") {
                // Regression guard: the UI shows an expected format
                // placeholder that assumes this exact shape. 5 hex
                // groups of 4 chars each, prefixed with SPLYNEK-.
                let k = LicenseValidator.issue(email: "shape@test.com")
                let parts = k.split(separator: "-").map(String.init)
                try expectEqual(parts.count, 6)   // SPLYNEK + 5 groups
                try expectEqual(parts[0], "SPLYNEK")
                for group in parts.dropFirst() {
                    try expectEqual(group.count, 4)
                    for ch in group {
                        try expect(ch.isHexDigit, "non-hex char in group: \(ch)")
                    }
                }
            }
        }

        TestHarness.suite("LicenseManager state machine") {

            TestHarness.test("Fresh init with empty defaults → free tier") {
                let defaults = UserDefaults(suiteName: "splynek-test-\(UUID())")!
                let mgr = LicenseManager(defaults: defaults)
                try expect(!mgr.isPro)
                try expect(mgr.licensedEmail == nil)
            }

            TestHarness.test("unlock() with valid credentials flips isPro + persists") {
                let defaults = UserDefaults(suiteName: "splynek-test-\(UUID())")!
                let mgr = LicenseManager(defaults: defaults)
                let key = LicenseValidator.issue(email: "buyer@example.com")
                try expect(mgr.unlock(email: "buyer@example.com", key: key))
                try expect(mgr.isPro)
                try expectEqual(mgr.licensedEmail, "buyer@example.com")
                // Persistence: a fresh manager reading the same
                // defaults should also come up Pro.
                let reborn = LicenseManager(defaults: defaults)
                try expect(reborn.isPro)
                try expectEqual(reborn.licensedEmail, "buyer@example.com")
            }

            TestHarness.test("unlock() with wrong key returns false + leaves state free") {
                let defaults = UserDefaults(suiteName: "splynek-test-\(UUID())")!
                let mgr = LicenseManager(defaults: defaults)
                try expect(!mgr.unlock(email: "buyer@example.com", key: "SPLYNEK-BAD-KEY"))
                try expect(!mgr.isPro)
                try expect(mgr.lastUnlockError != nil,
                           "unlock error should surface a user-facing reason")
            }

            TestHarness.test("deactivate() flips isPro back + wipes persisted key") {
                let defaults = UserDefaults(suiteName: "splynek-test-\(UUID())")!
                let mgr = LicenseManager(defaults: defaults)
                let key = LicenseValidator.issue(email: "x@y.com")
                _ = mgr.unlock(email: "x@y.com", key: key)
                mgr.deactivate()
                try expect(!mgr.isPro)
                try expect(mgr.licensedEmail == nil)
                // A reborn manager should also see free tier.
                try expect(!LicenseManager(defaults: defaults).isPro)
            }

            TestHarness.test("Tampered persisted key is ignored on load") {
                // Defence in depth: a user editing UserDefaults by
                // hand to put a bogus key shouldn't flip isPro on
                // relaunch.
                let defaults = UserDefaults(suiteName: "splynek-test-\(UUID())")!
                defaults.set("x@y.com", forKey: "splynekProEmail")
                defaults.set("SPLYNEK-FAKE-FAKE-FAKE-FAKE-FAKE", forKey: "splynekProKey")
                let mgr = LicenseManager(defaults: defaults)
                try expect(!mgr.isPro,
                           "invalid persisted credentials must not activate Pro")
            }
        }
    }
}
