import Foundation

/// A plan-then-execute download batch generated by the local LLM
/// (v0.42 "Agentic Download Recipes"). The LLM takes a plain-English
/// goal like *"set up my Mac for iOS development"* and returns a
/// structured list of candidate downloads with URLs, rationales, and
/// self-rated confidence scores. The user reviews the list, tweaks or
/// unselects items, and hits *Queue*; Splynek fans the selected items
/// into the queue with proper checksums + interface pinning.
///
/// Critical invariants:
///   - **Every item surfaces a `homepage` URL** so the user can verify
///     the LLM isn't hallucinating. Direct-download URLs without a
///     verifiable project page are the #1 risk here.
///   - **Every item has a `rationale`** — a one-sentence explanation of
///     why it's in the recipe. Forces the LLM to reason about each
///     pick and gives the user something to evaluate.
///   - **`confidence` is 0..1, LLM-self-rated.** Low-confidence items
///     (<0.7) render with a warning pill so users know to double-check.
///   - **`selected` starts true for all items** — the happy path is "I
///     typed my goal, I hit Queue, the batch runs overnight."
struct RecipeItem: Codable, Identifiable, Hashable, Sendable {
    var id: UUID = UUID()
    var name: String
    var url: String
    var homepage: String?
    var sha256: String?
    var sizeHint: String?
    var rationale: String
    /// 0.0 (complete guess) → 1.0 (canonical, well-known URL).
    /// Clamped to [0, 1] on parse.
    var confidence: Double
    var selected: Bool = true
}

struct DownloadRecipe: Codable, Identifiable, Hashable, Sendable {
    var id: UUID = UUID()
    var goal: String
    /// LLM-generated short title, e.g. "iOS development setup".
    var title: String
    var items: [RecipeItem]
    var generatedAt: Date
    /// Which Ollama model generated this recipe. Persisted so users
    /// can tell "the thing llama3 picked last week" from "the thing
    /// qwen picked today" when comparing results.
    var modelUsed: String
}

// MARK: - Parser (pure)

/// Parser extracted so the test harness can pin every tolerance case
/// (markdown fences, trailing prose, missing fields, garbage
/// confidence scores) without standing up the AIAssistant.
enum RecipeParser {

    enum ParseError: Error, CustomStringConvertible {
        case noJSONFound
        case decodeFailed(String)
        case noItems

        var description: String {
            switch self {
            case .noJSONFound:         return "no JSON object in the model's response"
            case .decodeFailed(let s): return "JSON didn't match the expected shape: \(s)"
            case .noItems:             return "recipe contained zero usable items"
            }
        }
    }

    /// Decode the LLM's raw response into a `DownloadRecipe`. Tolerates
    /// common LLM mis-behaviours: markdown fences around the JSON,
    /// trailing prose, leading "Here's the recipe:" chatter. Strict
    /// about the inner shape — missing required fields on an item
    /// drops that item rather than failing the whole batch.
    static func parse(
        response: String, goal: String, modelUsed: String, now: Date = Date()
    ) throws -> DownloadRecipe {
        guard let json = extractJSONObject(from: response) else {
            throw ParseError.noJSONFound
        }
        let data = Data(json.utf8)
        struct RawItem: Decodable {
            let name: String?
            let url: String?
            let homepage: String?
            let sha256: String?
            let sizeHint: String?
            let rationale: String?
            let confidence: Double?
        }
        struct RawRecipe: Decodable {
            let title: String?
            let items: [RawItem]?
        }
        guard let raw = try? JSONDecoder().decode(RawRecipe.self, from: data) else {
            throw ParseError.decodeFailed(String(json.prefix(200)))
        }
        let items: [RecipeItem] = (raw.items ?? []).compactMap { r in
            guard let name = r.name?.trimmingCharacters(in: .whitespacesAndNewlines),
                  !name.isEmpty,
                  let urlStr = r.url?.trimmingCharacters(in: .whitespacesAndNewlines),
                  !urlStr.isEmpty,
                  let url = URL(string: urlStr),
                  let scheme = url.scheme?.lowercased(),
                  scheme == "http" || scheme == "https",
                  let rationale = r.rationale?.trimmingCharacters(in: .whitespacesAndNewlines),
                  !rationale.isEmpty
            else {
                return nil
            }
            // QA P1 #2 (v0.43): the LLM's prompt forbids App Store
            // URLs, but LLMs don't always obey. Drop any item whose
            // URL is an obvious non-downloadable destination so the
            // queue never sees "Server doesn't advertise Range
            // support" failures from items we should have rejected
            // client-side.
            if isNonDownloadableHost(url: url) { return nil }
            // Homepage is optional but if present must also be http(s).
            var homepage = r.homepage?.trimmingCharacters(in: .whitespacesAndNewlines)
            if let h = homepage, let hurl = URL(string: h),
               hurl.scheme?.lowercased() != "http", hurl.scheme?.lowercased() != "https" {
                homepage = nil
            }
            // Confidence: clamp; default 0.5 if absent.
            let confidence = max(0, min(1, r.confidence ?? 0.5))
            // SHA-256: 64 hex chars or nothing.
            let sha = r.sha256?.trimmingCharacters(in: .whitespacesAndNewlines)
            let validSha: String? = {
                guard let s = sha, s.count == 64,
                      s.allSatisfy({ $0.isHexDigit })
                else { return nil }
                return s.lowercased()
            }()
            return RecipeItem(
                name: name,
                url: urlStr,
                homepage: homepage,
                sha256: validSha,
                sizeHint: r.sizeHint?.trimmingCharacters(in: .whitespacesAndNewlines),
                rationale: rationale,
                confidence: confidence,
                selected: true
            )
        }
        guard !items.isEmpty else { throw ParseError.noItems }
        let title = (raw.title?.trimmingCharacters(in: .whitespacesAndNewlines))
            ?? "Recipe for \(goal)"
        return DownloadRecipe(
            goal: goal,
            title: title.isEmpty ? "Recipe for \(goal)" : title,
            items: items,
            generatedAt: now,
            modelUsed: modelUsed
        )
    }

    /// Hosts that serve marketing pages rather than downloadable
    /// files. An LLM occasionally returns these as an item URL
    /// despite being told not to; the parser drops those items so
    /// they never reach the queue. Kept as a small explicit list
    /// rather than a generic "HEAD-check for Content-Length" so
    /// parsing stays offline + synchronous. Extend as new patterns
    /// show up in the wild.
    static func isNonDownloadableHost(url: URL) -> Bool {
        guard let host = url.host?.lowercased() else { return false }
        let bannedHosts = [
            "apps.apple.com",
            "itunes.apple.com",
            "music.apple.com",
            "tv.apple.com",
            "podcasts.apple.com",
            "play.google.com",
            "www.microsoft.com",   // Microsoft Store landing
            "apps.microsoft.com",
            "www.amazon.com",      // product detail pages
        ]
        return bannedHosts.contains(host)
    }

    /// Slice the first balanced `{ ... }` object out of a string that
    /// might be wrapped in markdown fences or prefixed with prose.
    /// LLMs frequently "helpfully" explain before dumping JSON even
    /// when told not to.
    static func extractJSONObject(from raw: String) -> String? {
        // Strip common markdown fence introductions.
        var s = raw
        if let range = s.range(of: "```json") ?? s.range(of: "```") {
            s = String(s[range.upperBound...])
        }
        // Find the first `{` and scan for a matched `}`, tracking
        // string quoting so braces inside JSON strings don't fool us.
        guard let start = s.firstIndex(of: "{") else { return nil }
        var depth = 0
        var inString = false
        var escape = false
        var i = start
        while i < s.endIndex {
            let c = s[i]
            if inString {
                if escape {
                    escape = false
                } else if c == "\\" {
                    escape = true
                } else if c == "\"" {
                    inString = false
                }
            } else {
                if c == "\"" {
                    inString = true
                } else if c == "{" {
                    depth += 1
                } else if c == "}" {
                    depth -= 1
                    if depth == 0 {
                        return String(s[start...i])
                    }
                }
            }
            i = s.index(after: i)
        }
        return nil
    }
}

// MARK: - Persistence

/// Disk-backed recent-recipes list. Users can revisit a past recipe
/// and re-queue (or partially re-queue) from the Recipes view.
private struct RecipeArchive: Codable {
    var recipes: [DownloadRecipe]
}

enum RecipeStore {

    /// Cap. Older recipes rolled off the tail once we hit this count
    /// — keeps the JSON under ~20 KB even with large recipes.
    static let maxStored = 20

    static var storeURL: URL {
        let fm = FileManager.default
        let base = (try? fm.url(
            for: .applicationSupportDirectory, in: .userDomainMask,
            appropriateFor: nil, create: true
        )) ?? fm.temporaryDirectory
        let dir = base.appendingPathComponent("Splynek", isDirectory: true)
        try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("recipes.json")
    }

    static func load() -> [DownloadRecipe] {
        guard let data = try? Data(contentsOf: storeURL) else { return [] }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        guard let archive = try? decoder.decode(RecipeArchive.self, from: data) else {
            return []
        }
        return archive.recipes.sorted { $0.generatedAt > $1.generatedAt }
    }

    static func save(_ recipes: [DownloadRecipe]) {
        let trimmed = Array(recipes
            .sorted { $0.generatedAt > $1.generatedAt }
            .prefix(maxStored))
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        guard let data = try? encoder.encode(RecipeArchive(recipes: trimmed)) else {
            return
        }
        try? data.write(to: storeURL, options: .atomic)
    }
}
