#!/usr/bin/env python3
"""
v1.6.2: compile Localizable.xcstrings → per-locale Localizable.strings.

**Why this exists.**  SwiftPM's `.process(...)` for `.xcstrings`
copies the raw catalog file into the resource bundle, but the
macOS Foundation runtime (in `swift build`-produced binaries) does
NOT read the `.xcstrings` format directly — it expects
`{locale}.lproj/Localizable.strings`.  Xcode runs the
`xcstringstool` step automatically; SwiftPM-from-CLI doesn't.

The result: a fully translated catalog ships with the .app, but
Foundation falls through to source English on every locale.

This script bridges that gap:

  1. Reads `Sources/SplynekCore/Localizable.xcstrings`
  2. Emits one `Localizable.strings` per locale
  3. Places each at `<bundle>/{locale}.lproj/Localizable.strings`
  4. Updates the bundle's Info.plist with CFBundleLocalizations

Run from `Scripts/build.sh` AFTER copying the SPM resource bundle
into the .app.

Usage:

  python3 Scripts/compile-xcstrings.py <bundle-path>
  # e.g. Scripts/compile-xcstrings.py build/Splynek.app/Contents/Resources/Splynek_SplynekCore.bundle
"""

import json
import plistlib
import sys
from pathlib import Path


def encode_strings_value(s: str) -> str:
    """Encode a string for the .strings file format.  Apple's format
    is C-string-like: backslash escapes for newline/tab/quote, double
    quotes around the value."""
    # Order matters — escape backslash first.
    out = (s.replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t"))
    return f'"{out}"'


def compile_xcstrings(catalog_path: Path, bundle_path: Path):
    catalog = json.loads(catalog_path.read_text())
    source_lang = catalog.get("sourceLanguage", "en")
    strings = catalog.get("strings", {})

    # Discover all locales.
    locales = set()
    for entry in strings.values():
        locales.update(entry.get("localizations", {}).keys())
    # Always include source language as a target so Foundation can
    # render it as a complete locale rather than relying on key-as-value
    # fallback.
    locales.add(source_lang)
    locales = sorted(locales)

    # Emit per-locale .strings files.
    for locale in locales:
        lproj = bundle_path / f"{locale}.lproj"
        lproj.mkdir(exist_ok=True)
        lines = [
            "/* Auto-generated by Scripts/compile-xcstrings.py.",
            f"   Source: {catalog_path.name}",
            f"   Locale: {locale}",
            "   DO NOT EDIT — edit the .xcstrings catalog instead. */",
            "",
        ]
        emitted = 0
        for key in sorted(strings.keys()):
            entry = strings[key]
            localizations = entry.get("localizations", {})
            if locale == source_lang:
                # Source language: use the key itself unless an explicit
                # localization is present (rare but possible).
                value = (localizations.get(locale, {})
                                       .get("stringUnit", {})
                                       .get("value", key))
            else:
                value = (localizations.get(locale, {})
                                       .get("stringUnit", {})
                                       .get("value"))
                if value is None:
                    # Fall back to source English so missing translations
                    # don't surface as raw keys to the user.
                    continue
            comment = entry.get("comment", "")
            if comment:
                lines.append(f"/* {comment} */")
            lines.append(
                f"{encode_strings_value(key)} = {encode_strings_value(value)};"
            )
            emitted += 1
        lines.append("")
        (lproj / "Localizable.strings").write_text("\n".join(lines))
        print(f"  {locale}: {emitted} strings → {lproj.name}/Localizable.strings")

    # Update the bundle's Info.plist.
    info_plist = bundle_path / "Info.plist"
    if info_plist.exists():
        with open(info_plist, "rb") as f:
            info = plistlib.load(f)
    else:
        info = {}
    info["CFBundleDevelopmentRegion"] = source_lang
    info["CFBundleLocalizations"] = locales
    with open(info_plist, "wb") as f:
        plistlib.dump(info, f)

    print(f"✓ {len(locales)} locales compiled into {bundle_path}")


def main():
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <bundle-path>", file=sys.stderr)
        sys.exit(2)
    bundle = Path(sys.argv[1])
    if not bundle.is_dir():
        print(f"error: bundle path does not exist: {bundle}", file=sys.stderr)
        sys.exit(2)
    catalog = bundle / "Localizable.xcstrings"
    if not catalog.is_file():
        print(f"error: no Localizable.xcstrings in {bundle}", file=sys.stderr)
        sys.exit(2)
    compile_xcstrings(catalog, bundle)


if __name__ == "__main__":
    main()
